[build]
command = "gatsby build"
publish = "public"

[dev]
command = "gatsby develop"
targetPort = 8000

[[redirects]]
from = "/index.html"
to = "/"
status = 301
force = true

[[redirects]]
from = "/:splat/index.html"
to = "/:splat/"
status = 301
force = true

[[redirects]]
from = "^/(.*)//+$"
to = "/$1/"
status = 301
force = true

[[redirects]]
from = "^/(.*[^/\\.])$"
to = "/$1/"
status = 301
force = true


[[redirects]]
from = "/materials/mocznik-krystaliczny-czysty-pheur-usp/"
to = "/materials/mocznik-farmaceutyczny-ph-eur-urea/"
status = 301

[[redirects]]
from = "/materials/sorbitol-t/"
to = "/materials/sorbitol-t-e420/"
status = 301

[[redirects]]
from = "/en/materials/sorbitol-t/"
to = "/en/materials/sorbitol-t-e420/"
status = 301

[[plugins]]
package = "@netlify/plugin-gatsby"

[[plugins]]
package = "@netlify/plugin-emails"
